# Generated by Django 6.1.1 on 2026-09-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='realisations/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='realisations/videos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('publiee', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
