# Generated by Django 6.1.1 on 2026-09-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_realisation_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('connexion', 'Connexion'), ('signalement', 'Signalement'), ('blocage', 'Blocage'), ('alerte', 'Alerte de sécurité')], max_length=20)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Journal de sécurité',
                'verbose_name_plural': 'Journal de sécurité',
                'ordering': ['-date_creation'],
            },
        ),
    ]
