# Generated by Django 6.1.1 on 2026-09-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journalsecurite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('premiere_visite', models.DateTimeField(auto_now_add=True)),
                ('derniere_visite', models.DateTimeField(auto_now=True)),
                ('page_actuelle', models.CharField(blank=True, max_length=500)),
                ('bloque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['-derniere_visite'],
            },
        ),
    ]
