# Generated by Django 6.1.1 on 2026-09-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='en_ligne',
            field=models.BooleanField(default=False),
        ),
    ]
