# Generated by Django 6.1.1 on 2026-09-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visiteur_en_ligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('motif', models.CharField(choices=[('bug', 'Bug ou problème technique'), ('abus', 'Abus ou comportement indésirable'), ('securite', 'Problème de sécurité'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traité')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
