# Generated by Django 6.1.1 on 2026-09-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_signalement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=100)),
                ('type_plafond', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='demandes_devis/')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('devis_envoye', 'Devis envoyé'), ('termine', 'Terminé')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-date_creation'],
            },
        ),
    ]
